# MA VERSION

version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-tests:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

  build-and-push-dockerhub:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build --build-arg arg_secret_key=SECRET_KEY -t docker-oc-lettings:circleci .
      - run:
          name: See Docker images
          command: docker images
      - run:
          name: Login to DockerHub
          command: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run:
          name: Link to DockerHub
          command: docker tag docker-oc-lettings:circleci $DOCKER_LOGIN/oc-lettings-site:$CIRCLE_SHA1
      - run:
          name: push Docker image
          command: docker push $DOCKER_LOGIN/oc-lettings-site:$CIRCLE_SHA1

  deploy-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - run:
          name: Pushing to heroku registry
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_APP_NAME} web
            #   pwd
            #   ls ./
            #   sed -i "s|os.getenv('SECRET_KEY')|'$(echo $SECRET_KEY | sed 's/&/\\&/g')'|g" ./oc_lettings_site/settings.py
            #   cat ./oc_lettings_site/settings.py | head -n 40
            #   git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build-test-deploy:
    jobs:
      - build-and-tests
      - build-and-push-dockerhub:
          filters:
            branches:
              only: master
          requires:
            - build-and-tests
      - deploy-heroku:
          filters:
            branches:
              only: master
          requires:
            - build-and-push-dockerhub
