# MA VERSION

version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-tests:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run tests
          command: pytest

  build-and-push-dockerhub:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build --build-arg secret_key_arg=$SECRET_KEY --build-arg sentry_addr_arg=$SENTRY_ADDR -t docker-oc-lettings:circleci .
      - run:
          name: See Docker images
          command: docker images
      - run:
          name: Login to DockerHub
          command: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run:
          name: Link to DockerHub
          command: docker tag docker-oc-lettings:circleci $DOCKER_LOGIN/oc-lettings-site:$CIRCLE_SHA1
      - run:
          name: push Docker image
          command: docker push $DOCKER_LOGIN/oc-lettings-site:$CIRCLE_SHA1
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - run:
          name: Upload to Heroku
          command: |
            docker tag docker-oc-lettings:circleci registry.heroku.com/${HEROKU_APP_NAME}/web:latest
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} docker push registry.heroku.com/${HEROKU_APP_NAME}/web:latest
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_APP_NAME} web

workflows:
  build-test-deploy:
    jobs:
      - build-and-tests
      - build-and-push-dockerhub:
          filters:
            branches:
              only: master
          requires:
            - build-and-tests
