# MA VERSION

version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: DEBUG print env variable
          command:
            echo $SECRET_KEY
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg arg_secret_key=SECRET_KEY -t heroku-oc-baptiste-dockerize:circleci .
            docker images

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Pushing to heroku registry
          command: |
            #  sudo curl https://cli-assets.heroku.com/install.sh | sh
            #   HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            #   HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${HEROKU_APP_NAME} web
            #   HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_APP_NAME} web
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
